name: イシューオープン

on:
  issues:
    types: [opened, edited]

jobs:
  show-event:
    name: イシューきたぞ
    runs-on: ubuntu-latest
    steps:
      - name: 環境変数
        run: env
      - name: イベントJSON(GITHUB_EVENT_PATH)ファイル
        run: cat ${GITHUB_EVENT_PATH}
