name: release

on:
  push:
    tags:
      - v*

jobs:
  release-cj:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up golang
        uses: actions/setup-go@v1

      - name: show env
        run: env | sort
      - name: Show event json
        run: cat ${GITHUB_EVENT_PATH}

      - name: go get miscellaneous
        run: |
          cd cj && go get -u github.com/${GITHUB_REPOSITORY}

      - name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

