name: testing github actions

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  run-test:
    name: running tests
  runs-on: ubuntu-latest
  env:
    FOO: bar-baz
  steps:
    - name: Setup Golang Environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show env
      run: make env
    - name: Run tests
      run: make test

